[package]
name = "geodate"
description = "Command line tool displaying the time in a new local geocentric date format"
version = "0.1.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
repository = "https://github.com/vinc/geodate"
homepage = "https://vinc.cc/projects/geodate.html"
license = "GPL-3.0+"

[dependencies]
time = "0.1"
lazy_static = "0.2"
